### ISSUE TITLE
Release UTC hero to additional content types.

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/particle#245]
Test UTC hero functionality and make it a sitewide block.

**Comment by brittrich** [comment]
@bmartinez287 and @UTCbridget. Related to this, I see a bit of improvement that can be done to the style of the default view. I think there are also few things I could add if they would be helpful:

- Option to align image at top instead of bottom (for banners used at bottom of page).
- Option to center vertical align? Similar to ND banner toward middle of page: https://www.nd.edu/faith-and-service/
- Do we like the lightblue color option? Is there something better? I'm not sure I love it.
- Anything else?

**Comment by bmartinez287** [comment]
Those are all great options. @UTCbridget had mentioned having a modified layout if the hero is within a container. Make it overflow it so it does not look flush. However, that might be hard to achieve.

**Comment by brittrich** [comment]
@UTCbridget is there an example out there of what you're thinking?

I don't now if this is related to the hero, maybe a different type of block, but is there a need for something to handle pages like this? https://www.utc.edu/enrollment-management-and-student-affairs where there is a need for an image inside of a container with alignment next to rich text options?

**Comment by UTCbridget** [comment]
The hero image in a section with a boxed container (not full) can also be indented instead of outdented if this is easier (which my guess it is) just as long as it is not flushed with the boxed container. When I see it flushed, it looks like a mistake since none of the other three sides are flushed. This is what I was thinking. This only applies to "boxed" sections.

![hero-outdent](https://user-images.githubusercontent.com/82905787/123095668-4e12b400-d3fc-11eb-893a-14a0392440e0.jpg)

![hero-indent](https://user-images.githubusercontent.com/82905787/123095683-51a63b00-d3fc-11eb-9c9e-1ce56b56f3e0.jpg)

**Comment by UTCbridget** [comment]
With regards to the light blue background, no I don't love it either. Perhaps lighter with 50% opacity may work? I'd have to play with it. Let me get back to you on this. I would like to work with it some to give options.

**Comment by brittrich** [comment]
> With regards to the light blue background, no I don't love it either. Perhaps lighter with 50% opacity may work? I'd have to play with it. Let me get back to you on this. I would like to work with it some to give options.

That would be great, just let me know what color (or even colors, if you want more options added) you think work well once you have time to tinker. Happy to add them in to this PR.
