### ISSUE TITLE
Hero prints url rather than placeholder text

### ISSUE THREAD

**Issue by bmartinez287** [UTCWeb/particle#351]
![Screen Shot 2021-10-25 at 5 15 08 PM](https://user-images.githubusercontent.com/39039024/138772131-e28ff56f-224c-4218-b821-dc00c56d832e.png)
@UTCbridget @brittrich 
The hero on the homepage seems to be printing the uri which makes me think we are missing an if statement there.

**Comment by bmartinez287** [comment]
Seems to be an issue if the link text is blank.
https://clouddev.utc.edu/
It does not let you without it but this will create an issue on a ton of hero blocks as they might be blank.

**Comment by brittrich** [comment]
I think this could be solved with an if / else statement, right? If there's text, use it, and if not, print "Learn More." Sorry, troubleshooting my setup now. If no one gets to it before tomorrow night I could work on it then if I get things running again. :)

**Comment by bmartinez287** [comment]
@brittrich yeah, that be great. If tomorrow works better that should be fine too.

**Comment by brittrich** [comment]
So, I did some looking, and what I thought might solve it doesn't...perhaps because it's just making the url the link text by default...so there is technically content in the field.

<img width="860" alt="Screen Shot 2021-10-27 at 12 17 02 AM" src="https://user-images.githubusercontent.com/50490141/138999189-e251e2c2-1c6c-40fe-9560-0605ebe5728e.png">

Maybe @UTCbridget has an idea? Or, now that the link text field is required, this won't be an issue moving forward except for items that are already created. How widespread is the hero in use on the site? Would it be possible to update those pages proactively before this reaches prod?

**Comment by bmartinez287** [comment]
I think its mostly used on the homepage and about pages. But we have to check with @UTCbridget if she used it somewhere else.

**Comment by UTCbridget** [comment]
I have only used it on homepage and about pages. I did, however, want to make it available for the admin/academic homepages as well.

**Comment by bmartinez287** [comment]
https://www.lullabot.com/articles/level-your-twiggery
I'm testing a few of those to avoid issues with it
![Screen Shot 2021-10-28 at 2 47 56 PM](https://user-images.githubusercontent.com/39039024/139326767-cced162c-b925-4521-9d75-434a34e1acce.png).
This is the title of all the blocks that could have an issue.

**Comment by brittrich** [comment]
Hey @bmartinez287, I took another look at this, but couldn't find another example of any heros without link text. I didn't know where to check for all the ones above, but made it through all the main landing pages linked from the Top Navigation and the Communities menu. I did a blt setup/sync beforehand, and it looks like the one that was a problem on the homepage is fixed as well. Basically, once the link has text, you can't delete it to get the url to appear again...the box will not allow for saving without text (by design). Any ideas on where else this might be an issue? Otherwise, I don't have a current example of the error to actually try to solve and no way to create one. :)
