### ISSUE TITLE
Newsroom page cards need to be 4 over 0 on lg and xl screens.

### ISSUE THREAD

**Issue by UTCbridget** [UTCWeb/particle#378]
The row of cards under the hero currently displays 3/1 on lg and xl screens. It only corrects past 1584px. All viewports 1024px and above need to display 4/0. Tweaks in CSS and/or Twig should fix this.

Current:

![Screen Shot 2021-12-08 at 8 45 54 AM](https://user-images.githubusercontent.com/82905787/145219302-1e4ee4f7-6429-4ca7-bffc-39d63b141e1a.png)

Should be: 

![Screen Shot 2021-12-08 at 8 44 35 AM](https://user-images.githubusercontent.com/82905787/145219330-2a4c26a3-a4a5-4ef4-97ab-ce114be16f4b.png)

**Comment by brittrich** [comment]
@UTCbridget I looked just a bit at what's going on with this one and it looks like it might work better as a grid instead of a flex if the number of cards will always be four (never less or more coming in from the rss)? The images are more statically sized that the other cards...so I think it might require some restructuring of the twig/tailwind to get something that will break evenly instead of fluidly. Happy to work on it if you haven't already gotten started on a fix.

**Comment by UTCbridget** [comment]
Go for it! I have not started on it yet. And grid works for me! Thank you!

**Comment by UTCbridget** [comment]
And it is always four.
