### ISSUE TITLE
Hover Image Block display at certain desktop browser widths needs text adjustment

### ISSUE THREAD

**Issue by UTCGilligan** [UTCWeb/particle#571]
**Describe the bug** 
Hover Image Block display at certain widths needs text adjustment. Text overflows container/background.

**To Reproduce**:

1. Go to [OPEIR Institutional Dashboards](https://www.utc.edu/academic-affairs/planning-evaluation-and-institutional-research/institutional-dashboards)
2. Adjust browser window width to around 1280 wide, responsive
3. Hover image
4. Text is too large for the container

**Expected behavior** 
Text fits within container/background.

**Screenshots**
![Screenshot 2023-06-29 at 09 06 46](https://github.com/UTCWeb/particle/assets/49878588/51c1f052-b283-49ef-ae85-07003007099e)

![Screenshot 2023-06-29 at 09 16 02](https://github.com/UTCWeb/particle/assets/49878588/18806548-58ad-479f-b0a1-804c027d5283)

**Desktop:**

- OS: any
- Browser: any
- Version any

**Smartphone:**

- Device: N/A

**Additional context**
The OPEIR Dashboards layout uses a 3-column layout builder layout with a hover image group inside each column, so the breakpoints might be tricky to account for.

**Comment by UTCbridget** [comment]
@UTCGilligan, the size and padding is based on the count of hovers in a row. The way they've built it is they've put a count of 1 hover (which presents large) per column in a three column section. If I fix for this globally, it could break in other instances. The ideal would've been for them to place three hovers in a row, but I understand why they did it this way. How bout I fix for this page exclusively on that page? Or better yet, instead of columns put the data in rows like the hovers were intended.

**Comment by UTCbridget** [comment]
Here is an example of how it would be laid out in rows instead of columns, which is how it was designed.
https://cloudtest.utc.edu/academic-affairs/planning-evaluation-and-institutional-research/institutional-dashboards

**Comment by UTCGilligan** [comment]
OK, thanks. I guess we can close this and suggest moving the hover image blocks to full width columns as you suggest. I was curious why the large text formatting got applied.
